export const ALL_QUESTIONS = [
  { id:1,  topic:"Core Philosophy",   question:"What is the primary philosophy behind PopDEX?", options:["Yield farming first","Incentive first","Trade First","Liquidity mining first"], correctIndex:2 },
  { id:2,  topic:"Market Strategy",    question:"According to the article, what do most Perp DEXs initially rely on?", options:["Institutional traders","Incentives and campaigns","On-chain order books","Brokers"], correctIndex:1 },
  { id:3,  topic:"Core Philosophy",   question:"PopDEX believes attention alone cannot build a:", options:["Token","Community","Durable trading venue","Layer 1"], correctIndex:2 },
  { id:4,  topic:"Ecosystem",         question:"Which group is NOT specifically mentioned as a value creator?", options:["Traders","LPs","Affiliates","NFT Artists"], correctIndex:3 },
  { id:5,  topic:"Product Focus",     question:"PopDEX is primarily focused on:", options:["Spot trading","NFT trading","Perpetual trading","Lending"], correctIndex:2 },
  { id:6,  topic:"Core Philosophy",   question:"What does PopDEX prioritize over passive speculation?", options:["Active contributors","Token holders","Validators","Miners"], correctIndex:0 },
  { id:7,  topic:"Infrastructure",    question:"PopDEX is built on:", options:["Ethereum","Solana","A purpose-designed Layer 1 blockchain","Polygon"], correctIndex:2 },
  { id:8,  topic:"Infrastructure",    question:"What trading infrastructure does PopDEX use?", options:["AMM","RFQ","Dark Pool","Fully On-Chain CLOB"], correctIndex:3 },
  { id:9,  topic:"Technical Knowledge",question:"What does CLOB stand for?", options:["Central Liquidity Order Base","Central Limit Order Book","Crypto Limit Order Bridge","Central Ledger Order Block"], correctIndex:1 },
  { id:10, topic:"Performance",       question:"What is PopDEX's target block time?", options:["1 second","500ms","200ms","100ms"], correctIndex:2 },
  { id:11, topic:"Performance",       question:"What TPS (Transactions Per Second) does PopDEX claim to support?", options:["10,000","50,000","75,000","100,000"], correctIndex:3 },
  { id:12, topic:"Trading Concepts",  question:"What does transparent price discovery refer to?", options:["Hidden orders","Publicly visible market pricing","OTC trading","Private settlement"], correctIndex:1 },
  { id:13, topic:"Capital Efficiency", question:"Superior capital efficiency is achieved through:", options:["Token burning","Margin optimization and risk management","Airdrops","Yield farming"], correctIndex:1 },
  { id:14, topic:"Liquidity",         question:"Deep liquidity helps achieve:", options:["Wider spreads","Higher fees","Tighter spreads","Slower execution"], correctIndex:2 },
  { id:15, topic:"Liquidity",         question:"Which feature contributes to market depth?", options:["Strategic liquidity partners","NFT staking","Governance voting","Token burning"], correctIndex:0 },
  { id:16, topic:"Product Vision",    question:"PopDEX aims to provide a trading experience comparable to:", options:["Traditional banks","Leading centralized exchanges","Social networks","NFT marketplaces"], correctIndex:1 },
  { id:17, topic:"Security",          question:"What key advantage does PopDEX preserve while offering CEX-like experience?", options:["Mining rewards","Self-custody","Custodial wallets","Fiat settlement"], correctIndex:1 },
  { id:18, topic:"Security",          question:"Institutional-grade security includes:", options:["Meme competitions","Advanced liquidation mechanisms","Token lotteries","Referral farming"], correctIndex:1 },
  { id:19, topic:"Product Launch",    question:"Which market category is mentioned at launch?", options:["Commodities only","Stocks only","Crypto and RWA perpetuals","Options only"], correctIndex:2 },
  { id:20, topic:"Terminology",       question:"What does RWA stand for?", options:["Real World Assets","Risk Weighted Allocation","Reward Wallet Access","Real Wealth Accounts"], correctIndex:0 },
  { id:21, topic:"Ecosystem",         question:"PopDEX is designed to integrate with:", options:["External protocols","Gaming consoles","Mobile carriers","Banks only"], correctIndex:0 },
  { id:22, topic:"Core Philosophy",   question:"Which statement best reflects PopDEX's belief?", options:["Value should return to creators of protocol activity","Value should remain in treasury","Value should only reward token holders","Value should only reward LPs"], correctIndex:0 },
  { id:23, topic:"Funding",           question:"How much funding did PopDEX raise?", options:["$10M","$20M","$30M","$50M"], correctIndex:2 },
  { id:24, topic:"Funding",           question:"Who led the funding round?", options:["Binance Labs","Paradigm","Foresight Ventures","Coinbase Ventures"], correctIndex:2 },
  { id:25, topic:"Funding",           question:"Which of the following is NOT listed as a use of the funding?", options:["Product development","Team expansion","Liquidity provision","Acquiring competitors"], correctIndex:3 },
  { id:26, topic:"PopLab",            question:"What is PopLab?", options:["Governance DAO","NFT Collection","Closed testing and co-building program","Liquidity vault"], correctIndex:2 },
  { id:27, topic:"PopLab",            question:"What is one objective of the PopLab testing phase?", options:["Meme creation","User experience improvement","NFT minting","Governance voting"], correctIndex:1 },
  { id:28, topic:"PopLab",            question:"Which area will PopLab specifically evaluate?", options:["Capital efficiency","Mining rewards","Validator staking","Token inflation"], correctIndex:0 },
  { id:29, topic:"Comprehension",     question:"Which statement is TRUE?", options:["PopDEX focuses mainly on short-term farming.","PopDEX rewards passive speculation.","PopDEX emphasizes real contributors and real market activity.","PopDEX is an NFT marketplace."], correctIndex:2 },
  { id:30, topic:"Core Vision",       question:"What best summarizes the PopDEX vision?", options:["Incentives first","Traders first, aligned value creation","Governance first","Yield farming first"], correctIndex:1 },
  { id:31, topic:"Hard Mode",         question:"Which feature most directly supports transparent price discovery?", options:["Referral system","Fully on-chain CLOB","Liquidity mining","Yield rewards"], correctIndex:1 },
  { id:32, topic:"Hard Mode",         question:"Which combination best reflects PopDEX's design priorities?", options:["Farming + Airdrops + Points","Trading Experience + Capital Efficiency + Value Return","NFTs + Gaming + Metaverse","Lending + Borrowing + Staking"], correctIndex:1 },
  { id:33, topic:"Hard Mode",         question:"Why is PopDEX's model described as \"better alignment\"?", options:["It rewards activity that creates real market value","It gives the highest token emissions","It removes all fees","It eliminates liquidations"], correctIndex:0 },
  { id:34, topic:"Market Strategy",    question:"What are the three core forces that drive crypto market prices?", options:["Fundamentals, Technicals, and Sentiment","Momentum, Perception, and Liquidity","Volume, Price, and News","Supply, Demand, and Regulation"], correctIndex:1 },
  { id:35, topic:"Trading Concepts",   question:"A coin that exactly mirrors the narrative leader without any new innovation is called:", options:["A Primitive","An Awakening Asset","A Beta Play","A Trend Coin"], correctIndex:2 },
  { id:36, topic:"Capital Efficiency", question:"In a properly managed portfolio, the maximum allocation to any single coin is:", options:["10% of portfolio","20% of portfolio","50% of portfolio","30% of portfolio"], correctIndex:3 },
  { id:37, topic:"Hard Mode",          question:"What is the minimum acceptable risk-reward ratio before entering a trade?", options:["5X return for 3X risk","30X return for 15X risk","10X return for 5X risk","2X return for 1X risk"], correctIndex:1 },
  { id:38, topic:"Trading Concepts",   question:"The first coin to pump and define a new market narrative is known as:", options:["A Beta Play","A Primitive","A Trend Coin","An Awakening Asset"], correctIndex:3 },
  { id:39, topic:"Market Strategy",    question:"When should you go long at the very first retest of a key support level?", options:["Always, to catch the early move","Only when high volume confirms","Never, because the first retest usually fails","Only on the daily timeframe"], correctIndex:2 },
  { id:40, topic:"Security",           question:"For proper risk management, the ideal maximum number of open positions at any time is:", options:["1 to 2 coins","10 or more coins","7 to 8 coins","3 to 4 coins"], correctIndex:3 },
  { id:41, topic:"Funding",            question:"For a short-term, news-driven speculative trade, the correct maximum portfolio allocation is:", options:["25% of portfolio","30% of portfolio","10% of portfolio","5% of portfolio"], correctIndex:2 },
  { id:42, topic:"Product Vision",     question:"Which information source carries the highest speculation potential for traders?", options:["X / Twitter (undigested, no visible ceiling)","Discord and Telegram communities","Mainstream crypto news websites","Paid research newsletters"], correctIndex:0 },
  { id:43, topic:"Comprehension",      question:"When price runs sharply with no pullback (a lock-out period), the correct response is:", options:["FOMO in before missing the move","Short the overextension immediately","Rotate everything to stablecoins","Assume smart money is positioning and wait for the perp cloud retest"], correctIndex:3 },
  { id:44, topic:"Funding",            question:"What is the participation reward for joining Trading Quiz Night EP2?", options:["+5 Engage Points","+10 Engage Points","+15 Engage Points","+30 Engage Points"], correctIndex:1 },
  { id:45, topic:"Ecosystem",          question:"Where is the official venue for Trading Quiz Night EP2?", options:["💬｜general-chat","📸｜event-lounge","🎙️｜stage","🎮｜gaming-room"], correctIndex:1 },
  { id:46, topic:"Comprehension",      question:"How many total questions will be asked during Trading Quiz Night EP2?", options:["10 questions","15 questions","20 questions","25 questions"], correctIndex:1 }
];

export const AI_NAMES = [
  { name:"CryptoKing", initials:"CK", color:"linear-gradient(135deg,#FFD23F,#FF9500)", textColor:"#1A0F00" },
  { name:"moonvault",  initials:"MV", color:"#8B35D9", textColor:"white" },
  { name:"axistrader", initials:"AX", color:"#00D4FF", textColor:"#06061A" },
  { name:"DeFiEdge",   initials:"DE", color:"#3C3C60", textColor:"#9090C0" },
  { name:"PopWhale",   initials:"PW", color:"#3733FF", textColor:"white" },
  { name:"0xTrader",   initials:"0x", color:"#A855F7", textColor:"white" },
  { name:"AlphaSeeker",initials:"AS", color:"#00D464", textColor:"#06061A" }
];
